### PR TITLE
adding the config as array not as a const of a class

### PR DESCRIPTION
**Pull request by zaherg**
i have change the way of the config, so instead of creating a class for
the config, and this will force you to have only one APP from
parse.com, you can just pass the config array to the constructor so
that you can now use the sam library with many apps based on the keys
not only one app.

### CODE REVIEW

**Comment by andrewscofield** [comment]
I fully understand the need to have the ability to change that config file on the fly, I'm just not a fan of the flow you've got going here. Let me try to think of some better ways to do this then creating a global `$config` variable.

**Comment by zaherg** [comment]
from my point of view, your global config glass is the same as the global `$config` variable ..
unless we have to do the config class as a fully (set / get) class to make it handy ..

**Comment by andrewscofield** [comment]
Well most people use this library within larger app frameworks, typically you wouldn't want to use global variables like that in that environment. I understand though if you aren't, many people also use this library standalone. I'm not saying your method is wrong, I'm saying it would break other people's setups. What you have done is shown the need for this type of setup. I'll leave a comment here when the new config class is ready

Yes, what I have in mind is a config class where you setup 'apps' which would return their specific parse.com keys.

**Comment by zaherg** [comment]
no problem, and if i have had the time to do more modifications, i will do my best to send you a pull request ..

**Comment by andrewscofield** [comment]
this here is not live, but a thought on how this might work: https://github.com/apotropaic/parse.com-php-library/commit/eba20179905de092c5054a903822c2f808ba560b

```
//assuming the config file is setup correctly the below should work fine
$parseProduction = new parseRestClient('production');
$parseStaging = new parseRestClient('staging');
$parseTest = new parseRestClient('test');
```

Does this fix the issue you were seeing?

**Comment by zaherg** [comment]
will, i think you missed my point ..
my app is working with clients, each one of them has his own parse.com information `APPID .. etc`, and thats why i found the global `$config` variable something easy to use, so i can fetch the data from db and add it to the config var and use it ..

your way make use only for 1 key ( static inside the config class ) in the whole app ..

**Comment by chadl** [comment]
I have the same issue/suggestion as @linuxjuggler.

I tend to use services like this (the parse sdk) in an inversion of control pattern, where the class is defined and the attributes (config) is injected at runtime.

I, as a developer, don't want config parameters like this hardcoded in some class (especially in constants or done statically or globally), which I can not manipulate unless I make code changes.  The library as it is is not easy to use/test in an enterprise system.

So I'd much rather see something like the original change that @linuxjuggler proposed or something like this:

```
class class parseConfig
{
  protected $_appid;
  protected $_masterkey;
  protected $_restkey;
  protected $_parseurl;

  public function setAppId($a)
  {
    $this->_appid = $a;
    return $this;
  }
  public function getAppId()
  {
    return $this->_appid;
  }
  // ... and so on...
}
```

Then, later, I can just inject in any number of parseConfig objects into the parse classes.  Who's to say you know if there are any number of the following environments....staging, prod, dev, test, pre-staging etc.  Leave those details up to the developers using the library.

**Comment by SinanEker** [comment]
@linuxjuggler  Just use eval!

``` php
$config = array(...);
eval("
class parseConfig
{
    const APPID = '".$config["appid"]."';
    const MASTERKEY = '".$config["masterkey"]."';
    const RESTKEY = '".$config["restkey"]."';
    const PARSEURL = '".$config["parseurl"]."';
}");
```

**Comment by zaherg** [comment]
@SinanEker : 
Caution The eval() language construct is very dangerous because it allows execution of arbitrary PHP code. Its use thus is discouraged. If you have carefully verified that there is no other option than to use this construct, pay special attention not to pass any user provided data into it without properly validating it beforehand.
http://php.net/manual/en/function.eval.php

and in my case

1- there is another option 
2- its a user input which i dont trust ..

thanks

**Comment by SinanEker** [comment]
@linuxjuggler I knew that problem, but I would never use user input in eval.
Also the performance of eval is terrible. 
But you could edit the source of parse.php

``` php
/* Line 23 to 28 */
    public function __construct()
    {
        $this->_appid = parseConfig::APPID;
        $this->_masterkey = parseConfig::MASTERKEY;
        $this->_restkey = parseConfig::RESTKEY;
        $this->_parseurl = parseConfig::PARSEURL;
        /* ... */
```

To:

``` php
    public function __construct(array $config = array())
    {
        if (isset($config["APPID"], $config["MASTERKEY"], $config["RESTKEY"], $config["PARSEURL"]))
        {
            $this->_appid = $config["APPID"],;
            $this->_masterkey = $config["MASTERKEY"];
            $this->_restkey = $config["RESTKEY"];
            $this->_parseurl = $config["PARSEURL"];
        }

        $this->_appid = parseConfig::APPID;
        $this->_masterkey = parseConfig::MASTERKEY;
        $this->_restkey = parseConfig::RESTKEY;
        $this->_parseurl = parseConfig::PARSEURL;
```

**Comment by zaherg** [comment]
@SinanEker just a small note , in your app the `$this->_appid` for example will always get the `parseConfig::APPID` value ..

our problem here is not finding the best way, but to see if its usable or not, and if it worth spending time to implement or not ..

to me i have found some of the problems, some i have reported, some i didnt and just update my internal code ..

am trying to write a small book about it (http://leanpub.com/jasminewebapp) it will not be perfect and will not be able to cover everything, but @apotropaic  has made a huge effort in this nice library and am always happy to read his comments ....

**Pull request closed without merging**
