### PR TITLE
parseACL class

### PR DESCRIPTION
**Pull request by kasperpihl**
Hey, I've needed a class to handle the ACL.
So I wrote one, also I modified parse.php with ACL function.
Take a look at it, and pull it if you want.
Thanks for the good work with this framework!

/Kasper

### CODE REVIEW

**Comment by jobrienski** [comment]
I made a few what I think are improvements.
You couldn't pass in an  existing ACL to modify.

```
class parseACL{
    public $acl;

    public function __construct($ACL = null) {
        $this->acl = $ACL ? $ACL : stdClass();
    }

    private function setAccessForKey($access,$key,$bool){
        if(!($access == 'read' || $access == 'write')) return;
        if($bool) $this->acl->$key->$access = true;
        else {
            if(isset($this->acl->$key)){ 
                unset($this->acl->$key->$access);
                if(sizeof((array)$this->acl->$key) == 0) unset($this->acl->$key);
            }
            if(sizeof((array)$this->acl) == 0) $this->acl = stdClass();
        }
    }
    public function setPublicReadAccess($bool){
        $this->setAccessForKey('read','*',$bool);
    }
    public function setPublicWriteAccess($bool){
        $this->setAccessForKey('write','*',$bool);
    }
    public function setReadAccessForId($userId,$bool){
        $this->setAccessForKey('read',$userId,$bool);
    }
    public function setWriteAccessForId($userId,$bool){
        $this->setAccessForKey('write',$userId,$bool);
    }
    public function setReadAccessForRole($role,$bool){
        $this->setAccessForKey('read','role:'.$role,$bool);
    }
    public function setWriteAccessForRole($role,$bool){
        $this->setAccessForKey('write','role:'.$role,$bool);
    }
}

```

**Comment by jobrienski** [comment]
Oh also this part of the comments is wrong:

```
$object->ACL($acl);
$object->save();
```

It only worked for me when I did:

```
$object->ACL = $acl->acl;
$object->save();
```

**Comment by kasperpihl** [comment]
Great to here with the improvements. I am gonna pull them in to my repo.
Yeah the comment should have said
$object->setACL($acl);

Den 21/09/2012 kl. 05.23 skrev James OBrien notifications@github.com:

Oh also this part of the comments is wrong:

$object->ACL($acl);
$object->save();

It only worked for me when I did:

$object->ACL = $acl->acl;
$object->save();

 —
Reply to this email directly or view it on
GitHubhttps://github.com/apotropaic/parse.com-php-library/pull/43#issuecomment-8754119.

**Comment by kasperpihl** [comment]
Ahh no sorry, I see. Well great you got it to work.

Den 21/09/2012 kl. 05.23 skrev James OBrien notifications@github.com:

Oh also this part of the comments is wrong:

$object->ACL($acl);
$object->save();

It only worked for me when I did:

$object->ACL = $acl->acl;
$object->save();

 —
Reply to this email directly or view it on
GitHubhttps://github.com/apotropaic/parse.com-php-library/pull/43#issuecomment-8754119.

**Comment by andrewscofield** [comment]
This looks great guys! Thanks for your work on this

**Pull request merged**
