### PR TITLE
Composer support

### PR DESCRIPTION
**Pull request by eminetto**
Added namespaces and Composer support

### CODE REVIEW

**Comment by Donjohn** [comment]
pls merge this commit, we really need it for frameworks like Symfony2

**Comment by andrewscofield** [comment]
Hey I'll take a look at it again... I was 90% done with a new version of the library that was composer ready when this came across. I haven't had time to finish my yet. So, let me check it out again this weekend and maybe it'll be a quick fix until I can get my new version up.

**Comment by Donjohn** [comment]
hi, any update on this feature ? meanwhile i did my own by copying the classes but can't be easy updated without composer.

Thx in advance.

**Comment by eminetto** [comment]
There is something can i do to help? :)

**Comment by antonCPU** [comment]
For those who want to have this repo via Composer, add this to your composer.json file:

``` json
{
    "repositories": [
        {
            "type": "package",
            "package": {
                "name": "apotropaic/parse.com-php-library",
                "version": "2.0",
                "source": {
                    "url": "https://github.com/apotropaic/parse.com-php-library",
                    "type": "git",
                    "reference": "master"
                },
                "autoload": {
                    "classmap": ["/"]
                }
            }
        }
    ],
    "require": {
        "apotropaic/parse.com-php-library": "2.0"
    },
    "scripts" : {
        "post-install-cmd": "<specify class to fix issues>",
        "post-update-cmd": "<the same class once again>"
    }
}
```

"scripts" section is required in order to fix a few issues:
1) In parse.php need to replace all "include" to "include_once" so it won't mess up with composer autoloader.
2) parseConfig.php should be added.
3) Typo in parseQuery.php, need to replace "installation" with "installations".

``` php
class ComposerFix
{
    public static function postInstall()
    {
        $source = __DIR__ . '/parseConfig';
        $distDir = __DIR__  . '/../../../vendor/apotropaic/parse.com-php-library';
        $dist = $distDir . '/parseConfig.php';

        copy($source, $dist);

        $fileName = $distDir . '/parseQuery.php';

        file_put_contents($fileName, str_replace("'installation'", "'installations'", file_get_contents($fileName)));

        $fileName = $distDir . '/parse.php';

        file_put_contents($fileName, str_replace('include ', 'include_once ', file_get_contents($fileName)));
    }
}
```

**Pull request closed without merging**
